### ISSUE TITLE
Possible to remove symbol ?

### ISSUE THREAD

**Issue by jamestapping** [popei69/samples#12]
Hiya, thanks for the great tuto. Question though, how would one remove the symbol ?

Thankyou

**Comment by jamestapping** [comment]
Answer : changing format to .decimal seems to de the trick thanks

**Comment by popei69** [comment]
Hey @jamestapping , can you point me to white article and / or project you are referring to? Is it currency symbol or another of those samples?

Thanks

**Comment by jamestapping** [comment]
HIya, yes it is this one specifically. https://benoitpasquier.com/currency-textfield-in-swiftui/

Thanks a lot.

James

**Comment by popei69** [comment]
Hey @jamestapping ,

If you don't need the symbol of the currency, you can try to override it

```swift
let numberFormatter = numberFormatter()
numberFormatter.numberStyle = .currency
numberFormatter.currencySymbol = ""
```

Good luck!
