### ISSUE TITLE
NumberSample

### ISSUE THREAD

**Issue by telcosolutions** [popei69/samples#3]
I've been looking for a solution to currency input and your's comes very close to doing what I need. I see these problems;
1. No way to load an initial value. Line 58 has the value = 10 but the field still displays as $0.00 and sending has 10. I've looked but don't code using UIKet so don't see why this happens
2. There is a rounding problem caused by 
     private var doubleValue: Double { 
      return (decimal as NSDecimalNumber).doubleValue 
    }
  Enter, for example 4.44 and you get 4.43. I would recommend that you change using doubleValue (line 171) to just
		value = NSDecimalNumber(decimal: decimal * 100).intValue
3. Move CurrencyField code to a separate file so it can easily be used.

Looking forward to a fix. 

George

**Comment by popei69** [comment]
Hey @telcosolutions , thanks for the feedback, I really appreciate it.

Regarding the point 2, I did notice and made a workaround but haven't pushed my code on this yet. You might have a better suggestion, I'll look into it.

I'll fix in the same time point 1 and 3. Will keep you posted. 

Thanks again
