### ISSUE TITLE
I can't read a post of you

### ISSUE THREAD

**Issue by nhatduong** [popei69/samples#9]
Hello popei69,

Yesterday, I've read a post of you, it's greate. But, morning it's not found. 
Please, can you check for me?

Link not found: https://benoitpasquier.com/advanced-concepts-uitableView-rxdatasource/

Thank you.

**Comment by popei69** [comment]
Hey @nhatduong , apologisee for the delay, it seems the link is incorrect and should be lowercased

https://benoitpasquier.com/advanced-concepts-uitableview-rxdatasource/

Can you share with me the source where you find the wrong link? i'll make an update for it. Thanks
